### ISSUE TITLE
UnitType.whatBuilds()

### ISSUE THREAD

**Issue by mig62** [vjurenka/BWMirror#1]
Hi!
I'm starting to use BWMirror v1.2 but I can't find out how to get which UnitType can produce a given UnitType.
I think it would be UnitType.whatBuilds() in BWAPI, but I can't find the corresponding method in BWMirror.
What am I missing?

**Comment by vjurenka** [comment]
Hello,
the method you mention, as well as several more have been added to BWMirror today!
Please upgrade to BWMirror 2.1 :)

Have a nice day.

**Comment by mig62** [comment]
That was fast! :)
At the moment I'm involved with another project but I'll upgrade as soon as I have some spare time.
Thank you
