### ISSUE TITLE
JavaDoc/Library mismatch

### ISSUE THREAD

**Issue by vyo** [vjurenka/BWMirror#17]
The current version of the online [JavaDoc](http://bwmirror.jurenka.sk/javadoc/index.html) is out of sync with the [library contents](https://github.com/vjurenka/BWMirror/blob/master/api/bwapi):

I will go and list any additional findings here, too, if that is OK. Will setup a pull request as soon as possible.

| Class | JavaDoc | Library |
| --- | --- | --- |
| `Unit.java` | `java public boolean isUnpowered()` | `java public boolean isPowered()` |

**Comment by vjurenka** [comment]
Thanks for the headups, didn't realize the javadoc isn't up to date.

**Comment by vyo** [comment]
You're welcome; I just checked, the javadoc in the repo is fine, as can be seen [here](https://github.com/vjurenka/BWMirror/blob/gh-pages/javadoc/bwapi/Unit.html) at line 2815.

It's just the website that is apparently out of date.

**Comment by vyo** [comment]
Just an FYI, I found another inconsistency in `Order.java`; I checked the repo and the API here is fine.
So I guess the [online doc](http://bwmirror.jurenka.sk/) just never got updated with the repo info.

**Comment by vjurenka** [comment]
The documentation is now at http://vjurenka.github.io/BWMirror/javadoc/ , this one should be up to date with each release.
