### ISSUE TITLE
BWTA2 Classes Incomplete

### ISSUE THREAD

**Issue by Shadowen** [vjurenka/BWMirror#20]
It seems like `Chokepoint` is missing some of the corresponding functions available in BWTA2. For example:

```
getRegions
const std::pair<Region*,Region*>& getRegions() const;
Returns the two regions the chokepoint connects.
```

```
getSides
const std::pair<BWAPI::Position,BWAPI::Position>& getSides() const;
Returns the two sides of the chokepoint.
```

https://bitbucket.org/auriarte/bwta2/wiki/Chokepoint.wiki#!chokepoint

Is this as intended, or has BWTA simply changed?

**Comment by vjurenka** [comment]
Thanks for spotting that those were missing! Both are now part of BWMirror (as of 2.5)
