### ISSUE TITLE
Unit::getTrainingQueue referenced in the javadocs seems to be missing.

### ISSUE THREAD

**Issue by timfennis** [vjurenka/BWMirror#21]
I want to map my units to the buildings that are producing said unit and was looking for a method to do so. isTraining references `getTrainingQueue` but I can't find said method anywhere.

Do you know of another reliable way of finding the unit  that's being trained in a building, or the building that a unit is being trained in?

**Comment by vjurenka** [comment]
Sorry for the late reply, I've added this method to the current release 2.5. Thanks for the report :)
