### ISSUE TITLE
wrong supplyRequired() in zerg drone?

### ISSUE THREAD

**Issue by F-I-D-O** [vjurenka/BWMirror#23]
Method UnitType.Zerg_Drone.supplyRequired() returns 2. I think it should return 1, am I right?

**Comment by vjurenka** [comment]
Hi,
this is working as intended. All supply counts in the BWAPI and thus in BWMirror are doubled, see the note here:  https://bwapi.github.io/class_b_w_a_p_i_1_1_player_interface.html#adbaf9b3cd274ea7de02022d487f623fa

Sorry this note didn't make it into the javadoc, I'll try to fix that in the next release.

**Comment by F-I-D-O** [comment]
Thank you for quick response!
