### ISSUE TITLE
onEnd is never being called

### ISSUE THREAD

**Issue by Darker** [vjurenka/BWMirror#4]
No matter how the game ends, the binaries do detect it:

```
+ Building Zerg_Overlord in Zerg_Larva
Unit morph event: Zerg_Egg from None
+ Building Zerg_Drone in Zerg_Larva
Match ended. <<THE BINARY DETECTED END END std::outed it
Waiting...
failed, disconnecting
Disconnected
Game table mapping not
```

But the on end callback got never called:

```
 public void onEnd() {
   System.out.println("END!");
   System.exit(0);
 }
```

**Comment by vjurenka** [comment]
Hi,
which BWMirror version are you using?

I was unable to replicate this (ie, my game always printed the END!) on BWMirror 2.2, waited until AI won.

**Comment by Darker** [comment]
I'm sorry. I didn't properly override the onEnd method. It has 1 boolean parameter which I omitted. Not it works as it's supposed to.
