### ISSUE TITLE
class Order missing  .toString() method.

### ISSUE THREAD

**Issue by roman-kiselenko** [vjurenka/BWMirror#7]
Looks like in this version `Order` class doesn't have `.toString()` method.
I used this method in previous `BWAPI`.
Can you add it? It is very helpful for debug purpose.

:pray:

**Comment by vjurenka** [comment]
Hi, I've added the method as you requested.
Please, update to 2.3 to see it returned :)

Thanks for noticing that it disappeared from 2.0
